#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-jarn.viewdoc
Version  : 2.4
Release  : 28
URL      : https://files.pythonhosted.org/packages/5c/14/fd7f5630254668d58975f191a7a9a20bb7747eead974c864f9597d117ab2/jarn.viewdoc-2.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/5c/14/fd7f5630254668d58975f191a7a9a20bb7747eead974c864f9597d117ab2/jarn.viewdoc-2.4.tar.gz
Summary  : Python documentation viewer
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pypi-jarn.viewdoc-bin = %{version}-%{release}
Requires: pypi-jarn.viewdoc-python = %{version}-%{release}
Requires: pypi-jarn.viewdoc-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(blessed)
BuildRequires : pypi(docutils)
BuildRequires : pypi(py)
BuildRequires : pypi(pygments)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
============
jarn.viewdoc
============
------------------------------------
Python documentation viewer
------------------------------------

%package bin
Summary: bin components for the pypi-jarn.viewdoc package.
Group: Binaries

%description bin
bin components for the pypi-jarn.viewdoc package.


%package python
Summary: python components for the pypi-jarn.viewdoc package.
Group: Default
Requires: pypi-jarn.viewdoc-python3 = %{version}-%{release}

%description python
python components for the pypi-jarn.viewdoc package.


%package python3
Summary: python3 components for the pypi-jarn.viewdoc package.
Group: Default
Requires: python3-core
Provides: pypi(jarn.viewdoc)
Requires: pypi(blessed)
Requires: pypi(docutils)
Requires: pypi(pygments)
Requires: pypi(setuptools)

%description python3
python3 components for the pypi-jarn.viewdoc package.


%prep
%setup -q -n jarn.viewdoc-2.4
cd %{_builddir}/jarn.viewdoc-2.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1646149866
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/viewdoc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
